Common_EventScript_FindItem::
	callnative GetItemBallIdAndAmountFromTemplate
	finditem VAR_RESULT VAR_0x8009
	end

SafariZone_South_EventScript_ItemAbsolite:: @ 82912F0
	finditem ITEM_ABSOLITE
	end

Slateport_EventScript_ItemAlakazite:: @ 82912F0
	finditem ITEM_ALAKAZITE
	end

MtPyre_EventScript_ItemBanettite:: @ 82912F0
	finditem ITEM_BANETTITE
	end

AbandonedShip_EventScript_ItemBeedrillite:: @ 82912F0
	finditem ITEM_BEEDRILLITE
	end

RuggedCave3_EventScript_ItemGlalitite:: @ 82912F0
	finditem ITEM_GLALITITE
	end

RuggedRoad_EventScript_ItemHeracronite:: @ 82912F0
	finditem ITEM_HERACRONITE
	end

NewMauville_Inside3F_ItemManectite:: @ 82912F0
	finditem ITEM_MANECTITE
	end

Route117_EventScript_ItemMawilite:: @ 82912F0
	finditem ITEM_MAWILITE
	end

MtPyre_EventScript_ItemMedichamite:: @ 82912F0
	finditem ITEM_MEDICHAMITE
	end

Route124_EventScript_ItemPinsirite:: @ 82912F0
	finditem ITEM_PINSIRITE
	end

Sootopolis_EventScript_ItemSablenite:: @ 82912F0
	finditem ITEM_SABLENITE
	end

Route111_DesertPass_EventScript_ItemSteelixite:: @ 82912F0
	finditem ITEM_STEELIXITE
	end

Faraway_Island_Cave_EventScript_ItemSmoothRock:: @ 82912F0
	finditem ITEM_SMOOTH_ROCK
	end

NamelessDungeon_EventScript_ItemNugget:: @ 82912F0
	finditem ITEM_NUGGET
	end

NamelessDungeon_EventScript_ItemFullRestore:: @ 82912F0
	finditem ITEM_FULL_RESTORE
	end

NamelessDungeon_EventScript_ItemDuskStone:: @ 82912F0
	finditem ITEM_DUSK_STONE
	end

NamelessDungeon_EventScript_ItemAssaultVest:: @ 82912F0
	finditem ITEM_ASSAULT_VEST
	end

NamelessDungeon_EventScript_ItemElectirizer:: @ 82912F0
	finditem ITEM_ELECTIRIZER
	end

NamelessDungeon_EventScript_ItemBlackSludge:: @ 82912F0
	finditem ITEM_BLACK_SLUDGE
	end

NamelessDungeon_EventScript_ItemPPMax:: @ 82912F0
	finditem ITEM_PP_MAX
	end

NamelessDungeon_EventScript_ItemMaxRevive:: @ 82912F0
	finditem ITEM_MAX_REVIVE
	end

NamelessDungeon_EventScript_ItemMaxElixir:: @ 82912F0
	finditem ITEM_MAX_ELIXIR
	end

Route123_EventScript_ItemAbomasite:: @ 82912F0
	finditem ITEM_ABOMASITE
	end

MeteorFalls_EventScript_ItemAerodactylite:: @ 82912F0
	finditem ITEM_AERODACTYLITE
	end

NewMauville_EventScript_ItemAmpharosite:: @ 82912F0
	finditem ITEM_AMPHAROSITE
	end

FieryPath_EventScript_ItemCharizarditeX:: @ 82912F0
	finditem ITEM_CHARIZARDITE_X
	end

ScorchedSlab_EventScript_ItemCharizarditeY:: @ 82912F0
	finditem ITEM_CHARIZARDITE_Y
	end

Lavaridge_EventScript_ItemHoundoominite:: @ 82912F0
	finditem ITEM_HOUNDOOMINITE
	end

Pacifidlog_EventScript_ItemKangaskhanite:: @ 82912F0
	finditem ITEM_KANGASKHANITE
	end

Littleroot_EventScript_ItemMewtwoniteX:: @ 82912F0
	finditem ITEM_MEWTWONITE_X
	end

EverGrande_EventScript_ItemMewtwoniteY:: @ 82912F0
	finditem ITEM_MEWTWONITE_Y
	end

JaggedPass_EventScript_ItemTyranitarite:: @ 82912F0
	finditem ITEM_TYRANITARITE
	end

PetalburgWoods_EventScript_ItemScizorite:: @ 82912F0
	finditem ITEM_SCIZORITE
	end

Route119_EventScript_ItemVenusaurite:: @ 82912F0
	finditem ITEM_VENUSAURITE
	end

BatlleFrontier_EventScript_ItemGengarite:: @ 82912F0
	finditem ITEM_GENGARITE
	end

SSTidal_EventScript_ItemBlastoisinite:: @ 82912F0
	finditem ITEM_BLASTOISINITE
	end



Route132_EventScript_ItemTM34:: @ 82912F0
	finditem ITEM_TM34
	end

VictoryRoad_EventScript_ItemTM35:: @ 82912F0
	finditem ITEM_TM35
	end

JaggedPass_EventScript_ItemTM43:: @ 82912F0
	finditem ITEM_TM43
	end

MtChimney_EventScript_ItemTM59:: @ 82912F0
	finditem ITEM_TM59
	end

MtPyre_EventScript_ItemTM61:: @ 82912F0
	finditem ITEM_TM61
	end

Route119_EventScript_ItemTM62:: @ 82912F0
	finditem ITEM_TM62
	end

GraniteCave_EventScript_ItemTM65:: @ 82912F0
	finditem ITEM_TM65
	end

Route134_EventScript_ItemTM80:: @ 829109A
	finditem ITEM_TM80
	end

SafariZone_North_EventScript_ItemTM53:: @ 82912BC
	finditem ITEM_TM53
	end

SafariZone_Southeast_EventScript_ItemTM93:: @ 82912F0
	finditem ITEM_TM93
	end

AquaHideout_B2F_EventScript_ItemTM97:: @ 829138C
	finditem ITEM_TM97
	end

RuggedCave3_EventScript_ItemTM79:: @ 82913CD
	finditem ITEM_TM79
	end

RuggedRoad_EventScript_ItemTM83:: @ 82913CD
	finditem ITEM_TM83
	end

SeafloorCavern_Room7_EventScript_ItemTM55:: @ 8291401
	finditem ITEM_TM55
	end

SkyPillar_4F_EventScript_ItemTM64:: @ 82913E7
	finditem ITEM_TM64
	end

VictoryRoad_B2F_EventScript_ItemTM81:: @ 82914B7
	finditem ITEM_TM81
	end

Route123_EventScript_ItemGyaradosite:: @ 82912F0
	finditem ITEM_GYARADOSITE
	end

JaggedPass_EventScript_ItemTM69:: @ 82912F0
	finditem ITEM_TM69
	end

FortreeCity_EventScript_ItemTM86:: @ 82912F0
	finditem ITEM_TM86
	end

MeteorFalls_B1F_2R_EventScript_ItemSalamencite:: @ 82911DF
	finditem ITEM_SALAMENCITE
	end

SouthernIsland_Interior_EventScript_ItemLatiasite:: @ 82912F0
	finditem ITEM_LATIASITE
	end

SouthernIsland_Interior_EventScript_ItemLatiosite:: @ 82912F0
	finditem ITEM_LATIOSITE
	end

FortreeCity_EventScript_Garchompite:: @ 82912F0
	finditem ITEM_GARCHOMPITE
	end

MauvilleCity_EventScript_Lopunnite:: @ 82912F0
	finditem ITEM_LOPUNNITE
	end

BattleFrontier_EventScript_Audinite:: @ 82912F0
	finditem ITEM_AUDINITE
	end
